services:
  - type: web
    name: portfolio-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.kdqmxqftmwmtyxmrauhy:SU3kafmNVoPLCRST@aws-0-us-east-1.pooler.supabase.com:5432/postgres
      - key: DB_USER
        value: postgres.kdqmxqftmwmtyxmrauhy
      - key: DB_PASSWORD
        value: SU3kafmNVoPLCRST
      - key: DB_HOST
        value: aws-0-us-east-1.pooler.supabase.com
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: postgres
      - key: DB_SSL
        value: "true"
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://portfolio-catolicasc.vercel.app
