services:
  - type: web
    name: portfolio-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:SU3kafmNVoPLCRST@db.kdqmxqftmwmtyxmrauhy.supabase.co:5432/postgres
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://portfolio-catolicasc.vercel.app
